In [1]:
# Creating random 3x3 matrices to look for a pattern

import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as LA

rng = np.random.default_rng()


for i in range(5):

    A = rng.integers(0,2,(3,3))
    detA = LA.det(A)
    print(A,detA)
    



[[0 1 1]
 [1 1 1]
 [0 0 1]] -1.0
[[1 0 1]
 [0 1 1]
 [0 1 0]] -1.0
[[0 1 1]
 [1 1 0]
 [0 1 0]] 1.0
[[1 0 1]
 [0 0 1]
 [0 1 1]] -1.0
[[1 0 0]
 [1 0 0]
 [1 1 0]] 0.0


In [2]:
#Repeating this for 50 matrices

for i in range(50):

    A = rng.integers(0,2,(3,3))
    detA = LA.det(A)
    print(A,detA)
    


[[0 0 0]
 [0 0 1]
 [0 0 1]] 0.0
[[1 0 1]
 [0 0 0]
 [0 1 0]] 0.0
[[0 0 0]
 [0 0 0]
 [0 0 0]] 0.0
[[1 1 1]
 [0 0 0]
 [1 0 0]] 0.0
[[1 1 1]
 [1 0 0]
 [1 0 1]] -1.0
[[0 1 1]
 [1 1 1]
 [0 1 1]] 0.0
[[1 0 0]
 [0 1 1]
 [1 1 0]] -1.0
[[1 0 0]
 [0 1 0]
 [0 1 0]] 0.0
[[1 0 1]
 [0 0 1]
 [1 1 0]] -1.0
[[1 1 1]
 [1 1 1]
 [1 1 0]] 0.0
[[1 1 0]
 [1 1 1]
 [1 0 0]] 1.0
[[0 1 0]
 [0 0 0]
 [1 0 0]] 0.0
[[1 1 1]
 [0 0 0]
 [1 0 0]] 0.0
[[0 1 1]
 [0 0 0]
 [1 1 0]] 0.0
[[1 0 1]
 [1 0 1]
 [1 0 1]] 0.0
[[0 0 1]
 [0 1 0]
 [0 1 1]] 0.0
[[0 1 1]
 [1 0 1]
 [0 0 0]] 0.0
[[1 0 1]
 [1 0 0]
 [0 0 0]] 0.0
[[0 1 0]
 [1 0 1]
 [0 0 1]] -1.0
[[0 1 1]
 [0 1 0]
 [0 1 0]] 0.0
[[1 1 1]
 [0 1 1]
 [0 1 0]] -1.0
[[1 0 1]
 [1 1 1]
 [0 0 0]] 0.0
[[1 0 0]
 [1 0 1]
 [0 1 0]] -1.0
[[1 0 0]
 [0 0 0]
 [0 0 0]] 0.0
[[1 0 0]
 [0 1 1]
 [0 1 0]] -1.0
[[0 1 0]
 [1 0 0]
 [1 0 0]] 0.0
[[1 0 0]
 [1 0 1]
 [1 1 0]] -1.0
[[0 0 1]
 [1 0 0]
 [1 0 0]] 0.0
[[1 1 0]
 [0 1 0]
 [1 1 0]] 0.0
[[1 0 0]
 [1 0 1]
 [1 1 1]] -1.0
[[1 0 0]
 [0 1 1]
 [0 0 1]] 1.0

In [ ]:
import random
EMPTY = " "

def display(board): #Prints the board
    print("\n\t", board[0], "|", board[1], "|", board[2])
    print("\t","---------")
    print("\t",board[3], "|", board[4], "|", board[5])
    print("\t","---------")
    print("\t",board[6], "|", board[7], "|", board[8])

def legal_moves(board): #List of legal moves
    moves = []
    for entry in range(9):
        if board[entry] == EMPTY:
            moves.append(entry)
    return moves

def my_move(board): #Me making my move checking its allowed
    legal = legal_moves(board)
    move = None
    while move not in legal:
        move = int(input("Where will you move? (0 - 8):"))
        if move not in legal:
            print("\nThat square is already occupied\n")
    return move

def computer_move(board): #Creating a computer generated move randomly
    board = board[:]
    moves = legal_moves(board)
    i = random.choice(moves)
    return i

def game(): #Play the game
    print(
    """
                    0 | 1 | 2
                    ---------
                    3 | 4 | 5
                    ---------
                    6 | 7 | 8
    """
    ) #Printing how to play
    computer = '1'
    me = '0'
    board = []
    for square in range(9):
        board.append(EMPTY) #Producing the board
    first = input("Do I got first? (y/n): ")
    if first == 'y':
        turn = me
    else:
        turn = computer
    while EMPTY in board: #While the board is not full lets play
        if turn == me:
            move = my_move(board)
            board[move] = me
            turn = computer
        else:
            move = computer_move(board)
            board[move] = computer
            turn = me
        display(board)
    print('Game over')

game()


                    0 | 1 | 2
                    ---------
                    3 | 4 | 5
                    ---------
                    6 | 7 | 8
    
